import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import DefaultProviders from "@/components/default-providers";
import { Flex } from "@chakra-ui/react";

const dm_sans = DM_Sans({ 
  subsets: ['latin'],
  weight: '500',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dm_sans.className}>
        <DefaultProviders>
          <Flex minH='100vh' flexDirection='column' bgColor='#F2F4F7' >
            {children}
          </Flex>
        </DefaultProviders> 
      </body>
    </html>
  );
}
