import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import DefaultProviders from "@/components/default-providers";
import { Flex } from "@chakra-ui/react";

const dm_sans = DM_Sans({ 
  subsets: ['latin'],
  weight: '500',
})

export const metadata: Metadata = {
  title: "Paging system",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dm_sans.className} >
        <DefaultProviders>
          <Flex 
            minH='100vh' 
            flexDirection='column' 
            bgGradient='linear(to-r, gray.600, purple.200)'
          >
            {children}
          </Flex>
        </DefaultProviders> 
      </body>
    </html>
  );
}
